#
# Data structure to store win/draw/loss counts
# for each square and each piece type in regards
# to the given game phase
#

# heatmaps
heatmaps = {
    'opening': {
        'P': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'N': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'B': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'R': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'Q': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'K': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
         
        'p': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'n': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'b': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'r': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'q': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'k': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
    },
        
    'endgame': {
        'P': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'N': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'B': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'R': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'Q': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'K': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
         
        'p': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'n': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'b': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'r': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'q': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
        
        'k': [
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
                {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0}, {'win': 0, 'loss': 0, 'draw': 0},
             ],
    }
}
